import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-slate-700 text-slate-100 h-screen flex flex-col">
        <TRPCReactProvider>
          <NavBar />
          <main className="flex-grow">{children}</main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

const NavBar = () => {
  return (
    <nav className="flex h-1/20 flex-wrap items-center justify-between bg-slate-900 p-6">
      {/* Home nav item */}
      <a href="/" className="text-white">
        Home
      </a>
    </nav>
  );
};
