import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex h-screen flex-col bg-slate-700 text-slate-100">
        <TRPCReactProvider>
          <NavBar />
          <main className="flex-grow">{children}</main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

const NavBar = () => {
  return (
    <nav className="h-1/20 flex flex-wrap items-center justify-between bg-slate-900 p-6 text-l">
      {/* Home nav item */}
      <Link href="/">Home</Link>
      <Link href="/login">Log in</Link>
    </nav>
  );
};
